apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
      metadata:
        labels:
          app: expiration
      spec:
        containers:
          - name: expiration
            image: us.gcr.io/ticketing-dev-305703/expiration
            env:
              - name: NATS_CLIENT_ID
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: NATS_URL
                value: 'http://nats-service:4222'
              - name: NATS_CLUSTER_ID
                value: tickets
              - name: REDIS_HOST
                value: expiration-redis-service
